### Get semua catatan
GET http://localhost:3000/api/notes

### Tambah catatan
POST http://localhost:3000/api/notes
Content-Type: application/json

{
  "judul": "Testing",
  "isi": "Coba Isi Catatan."
}

### Edit catatan (ganti ID)
PUT http://localhost:3000/api/notes/7
Content-Type: application/json

{
  "judul": "Testing - Updated",
  "isi": "Sudah diedit"
}

### Hapus catatan
DELETE http://localhost:3000/api/notes/1